name: push
on:
  push:
    tags:
      - "v*"

jobs:
  windows-build:
    runs-on: windows-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@master

      - name: Set up Python 3.8
        uses: actions/setup-python@master
        with: { python-version: 3.8 }

      - name: Upgrade pip
        run: python -m pip install --upgrade pip PyInstaller

      - name: build
        run: pyinstaller -F install_mod_resource.py
  
      - name: upload
        uses: actions/upload-artifact@v1
        with:
          name: sample-windows
          path: dist/install_mod_resource.exe
